CREATE (:ProperName{ Name: "AND SIRIUS BLACK WAS STANDING OVER ME"})
CREATE (:ProperName{ Name: "HOLDING"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AND SIRIUS BLACK WAS STANDING OVER ME"
MATCH (b:ProperName)
WHERE b.Name = "HOLDING"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "KNIFE"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AND SIRIUS BLACK WAS STANDING OVER ME"
MATCH (b:ProperName)
WHERE b.Name = "KNIFE"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "PROFESSOR"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AND SIRIUS BLACK WAS STANDING OVER ME"
MATCH (b:ProperName)
WHERE b.Name = "PROFESSOR"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "WOKE UP"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AND SIRIUS BLACK WAS STANDING OVER ME"
MATCH (b:ProperName)
WHERE b.Name = "WOKE UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "AROUND AFTER DARK"})
CREATE (:ProperName{ Name: "HARRY"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AROUND AFTER DARK"
MATCH (b:ProperName)
WHERE b.Name = "HARRY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "YOU TWO"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "AROUND AFTER DARK"
MATCH (b:ProperName)
WHERE b.Name = "YOU TWO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Aberdeen"})
CREATE (:ProperName{ Name: "Anglesea"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aberdeen"
MATCH (b:ProperName)
WHERE b.Name = "Anglesea"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Accidental Magic Reversal Department"})
CREATE (:ProperName{ Name: "Miss Marjorie Dursley"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Accidental Magic Reversal Department"
MATCH (b:ProperName)
WHERE b.Name = "Miss Marjorie Dursley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Privet Drive"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Accidental Magic Reversal Department"
MATCH (b:ProperName)
WHERE b.Name = "Privet Drive"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Acid Pop"})
CREATE (:ProperName{ Name: "Ron"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Acid Pop"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Acid Pops"})
CREATE (:ProperName{ Name: "And"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Acid Pops"
MATCH (b:ProperName)
WHERE b.Name = "And"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Jelly Slugs"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Acid Pops"
MATCH (b:ProperName)
WHERE b.Name = "Jelly Slugs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Against"})
CREATE (:ProperName{ Name: "Dark Arts"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Against"
MATCH (b:ProperName)
WHERE b.Name = "Dark Arts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Agriculture"})
CREATE (:ProperName{ Name: "Fisheries"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Agriculture"
MATCH (b:ProperName)
WHERE b.Name = "Fisheries"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "The Ministry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Agriculture"
MATCH (b:ProperName)
WHERE b.Name = "The Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Aids"})
CREATE (:ProperName{ Name: "Magical Mischief-Makers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aids"
MATCH (b:ProperName)
WHERE b.Name = "Magical Mischief-Makers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "THE MARAUDER"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aids"
MATCH (b:ProperName)
WHERE b.Name = "THE MARAUDER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Albus Dumbledore"})
CREATE (:ProperName{ Name: "Harry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Albus Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Alicia Spinner"})
CREATE (:ProperName{ Name: "Angelina Johnson"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia Spinner"
MATCH (b:ProperName)
WHERE b.Name = "Angelina Johnson"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gryffindor"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia Spinner"
MATCH (b:ProperName)
WHERE b.Name = "Gryffindor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Katie Bell"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia Spinner"
MATCH (b:ProperName)
WHERE b.Name = "Katie Bell"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Quaffle"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia Spinner"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Alicia Spinnet"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia Spinnet"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Alicia"})
CREATE (:ProperName{ Name: "Quaffle Out"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Alicia"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle Out"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "All Occasions"})
CREATE (:ProperName{ Name: "Robes"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "All Occasions"
MATCH (b:ProperName)
WHERE b.Name = "Robes"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ancient Runes"})
CREATE (:ProperName{ Name: "Care"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ancient Runes"
MATCH (b:ProperName)
WHERE b.Name = "Care"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Divination"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ancient Runes"
MATCH (b:ProperName)
WHERE b.Name = "Divination"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Magical Creatures"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ancient Runes"
MATCH (b:ProperName)
WHERE b.Name = "Magical Creatures"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Muggle Studies"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ancient Runes"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Studies"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Study"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ancient Runes"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "And"
MATCH (b:ProperName)
WHERE b.Name = "Jelly Slugs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "George"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina Johnson"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Gryffindor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Katie Bell"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Peppermint Toads"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Peppermint Toads"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Angelina"})
CREATE (:ProperName{ Name: "Johnson"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina"
MATCH (b:ProperName)
WHERE b.Name = "Johnson"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Slytherin Keeper"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Angelina"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin Keeper"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Animagi"})
CREATE (:ProperName{ Name: "Professor McGonagall"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Animagi"
MATCH (b:ProperName)
WHERE b.Name = "Professor McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Another"})
CREATE (:ProperName{ Name: "Mum"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Another"
MATCH (b:ProperName)
WHERE b.Name = "Mum"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Any"})
CREATE (:ProperName{ Name: "Professor"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Any"
MATCH (b:ProperName)
WHERE b.Name = "Professor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Anything"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Anything"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Apparate"})
CREATE (:ProperName{ Name: "Maybe"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Apparate"
MATCH (b:ProperName)
WHERE b.Name = "Maybe"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "April"})
CREATE (:ProperName{ Name: "Dangerous Creatures"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "April"
MATCH (b:ProperName)
WHERE b.Name = "Dangerous Creatures"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Argyllshire"})
CREATE (:ProperName{ Name: "Hiding"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Argyllshire"
MATCH (b:ProperName)
WHERE b.Name = "Hiding"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Arithmancy"})
CREATE (:ProperName{ Name: "Professor Vector"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Arithmancy"
MATCH (b:ProperName)
WHERE b.Name = "Professor Vector"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Arithmancy"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Those"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Arithmancy"
MATCH (b:ProperName)
WHERE b.Name = "Those"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Arry Potter"})
CREATE (:ProperName{ Name: "You-Know"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Arry Potter"
MATCH (b:ProperName)
WHERE b.Name = "You-Know"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Arthur"})
CREATE (:ProperName{ Name: "Well"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Arthur"
MATCH (b:ProperName)
WHERE b.Name = "Well"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ashamed"})
CREATE (:ProperName{ Name: "Your Headship"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ashamed"
MATCH (b:ProperName)
WHERE b.Name = "Your Headship"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ask McGonagall"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ask McGonagall"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "At"})
CREATE (:ProperName{ Name: "Percy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "At"
MATCH (b:ProperName)
WHERE b.Name = "Percy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Aunt Marge"})
CREATE (:ProperName{ Name: "Do-It-Yourself Broomcare"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aunt Marge"
MATCH (b:ProperName)
WHERE b.Name = "Do-It-Yourself Broomcare"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Handbook"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aunt Marge"
MATCH (b:ProperName)
WHERE b.Name = "Handbook"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Aunt Margo"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aunt Margo"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Aunt Petunia"})
CREATE (:ProperName{ Name: "For"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Aunt Petunia"
MATCH (b:ProperName)
WHERE b.Name = "For"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Azkaban"})
CREATE (:ProperName{ Name: "Prisoner"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Azkaban"
MATCH (b:ProperName)
WHERE b.Name = "Prisoner"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "BANG"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "BANG"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bad"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bad"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Banges"})
CREATE (:ProperName{ Name: "Dervish"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Banges"
MATCH (b:ProperName)
WHERE b.Name = "Dervish"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Banges"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Zonko"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Banges"
MATCH (b:ProperName)
WHERE b.Name = "Zonko"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bathilda Bagshot"})
CREATE (:ProperName{ Name: "History"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bathilda Bagshot"
MATCH (b:ProperName)
WHERE b.Name = "History"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Magic"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bathilda Bagshot"
MATCH (b:ProperName)
WHERE b.Name = "Magic"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Beater"})
CREATE (:ProperName{ Name: "Fred Weasley"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Beater"
MATCH (b:ProperName)
WHERE b.Name = "Fred Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Behind"})
CREATE (:ProperName{ Name: "Slytherin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Behind"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Belch Powder"})
CREATE (:ProperName{ Name: "Stink Pellets"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Belch Powder"
MATCH (b:ProperName)
WHERE b.Name = "Stink Pellets"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Whizzing Worms"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Belch Powder"
MATCH (b:ProperName)
WHERE b.Name = "Whizzing Worms"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bell"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bell"
MATCH (b:ProperName)
WHERE b.Name = "Johnson"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Potter"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bell"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Spinnet"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bell"
MATCH (b:ProperName)
WHERE b.Name = "Spinnet"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Weasley"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bell"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wood"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bell"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Best"})
CREATE (:ProperName{ Name: "Madam Marsh"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Best"
MATCH (b:ProperName)
WHERE b.Name = "Madam Marsh"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Stan"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Best"
MATCH (b:ProperName)
WHERE b.Name = "Stan"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bill"})
CREATE (:ProperName{ Name: "Egypt"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bill"
MATCH (b:ProperName)
WHERE b.Name = "Egypt"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gringotts Wizarding Bank"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bill"
MATCH (b:ProperName)
WHERE b.Name = "Gringotts Wizarding Bank"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bill"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Black"})
CREATE (:ProperName{ Name: "Blacks"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "Blacks"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "But James Potter"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "But James Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "James Potter"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "James Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Magical Law Enforcement Squad"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "Magical Law Enforcement Squad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Malfoys"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "Malfoys"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Playing"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Black"
MATCH (b:ProperName)
WHERE b.Name = "Playing"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Do"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blacks"
MATCH (b:ProperName)
WHERE b.Name = "Do"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Fudge"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blacks"
MATCH (b:ProperName)
WHERE b.Name = "Fudge"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Minister"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blacks"
MATCH (b:ProperName)
WHERE b.Name = "Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Blotts"})
CREATE (:ProperName{ Name: "Death Omens"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blotts"
MATCH (b:ProperName)
WHERE b.Name = "Death Omens"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Flourish"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blotts"
MATCH (b:ProperName)
WHERE b.Name = "Flourish"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Madam Malkin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Blotts"
MATCH (b:ProperName)
WHERE b.Name = "Madam Malkin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bludger"})
CREATE (:ProperName{ Name: "Bole"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludger"
MATCH (b:ProperName)
WHERE b.Name = "Bole"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludger"
MATCH (b:ProperName)
WHERE b.Name = "Fred Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludger"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle Out"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ravenclaw Beaters"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludger"
MATCH (b:ProperName)
WHERE b.Name = "Ravenclaw Beaters"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Bludgers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludgers"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bludgers"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Derrick"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Bole"
MATCH (b:ProperName)
WHERE b.Name = "Derrick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Britain"})
CREATE (:ProperName{ Name: "Muggle"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Britain"
MATCH (b:ProperName)
WHERE b.Name = "Muggle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Shrieking Shack"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Britain"
MATCH (b:ProperName)
WHERE b.Name = "Shrieking Shack"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "British Muggles"})
CREATE (:ProperName{ Name: "Home Life"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "British Muggles"
MATCH (b:ProperName)
WHERE b.Name = "Home Life"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Social Habits"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "British Muggles"
MATCH (b:ProperName)
WHERE b.Name = "Social Habits"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Broken Balls"})
CREATE (:ProperName{ Name: "Insulate Yourself Against Shocks"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Broken Balls"
MATCH (b:ProperName)
WHERE b.Name = "Insulate Yourself Against Shocks"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Predicting"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Broken Balls"
MATCH (b:ProperName)
WHERE b.Name = "Predicting"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Unpredictable"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Broken Balls"
MATCH (b:ProperName)
WHERE b.Name = "Unpredictable"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "When Fortunes Turn Foul"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Broken Balls"
MATCH (b:ProperName)
WHERE b.Name = "When Fortunes Turn Foul"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Brown"})
CREATE (:ProperName{ Name: "Magnolia Crescent"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Brown"
MATCH (b:ProperName)
WHERE b.Name = "Magnolia Crescent"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Buckbeaks"})
CREATE (:ProperName{ Name: "Committee"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Buckbeaks"
MATCH (b:ProperName)
WHERE b.Name = "Committee"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Disposal"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Buckbeaks"
MATCH (b:ProperName)
WHERE b.Name = "Disposal"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "But Harry"})
CREATE (:ProperName{ Name: "Hogwarts"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "But Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "CHEATING"})
CREATE (:ProperName{ Name: "THAT"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CHEATING"
MATCH (b:ProperName)
WHERE b.Name = "THAT"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "THIRTY-ZERO"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CHEATING"
MATCH (b:ProperName)
WHERE b.Name = "THIRTY-ZERO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "YOU DIRTY"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CHEATING"
MATCH (b:ProperName)
WHERE b.Name = "YOU DIRTY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "YOU FILTHY"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CHEATING"
MATCH (b:ProperName)
WHERE b.Name = "YOU FILTHY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "CONTACT ME AGAIN"})
CREATE (:ProperName{ Name: "KNOW WHAT SCHOOL YOURE TALKING ABOUT"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CONTACT ME AGAIN"
MATCH (b:ProperName)
WHERE b.Name = "KNOW WHAT SCHOOL YOURE TALKING ABOUT"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "CROOKSHANKS"})
CREATE (:ProperName{ Name: "NO"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "CROOKSHANKS"
MATCH (b:ProperName)
WHERE b.Name = "NO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Captain Flint"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain Flint"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Captain"})
CREATE (:ProperName{ Name: "Cedric Diggory"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Cedric Diggory"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Crabbe"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Crabbe"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Goyle"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Goyle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Gryffindor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Marcus Flint"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Marcus Flint"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "O1iver Wood"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "O1iver Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Quidditch"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Seeker"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Seeker"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Captain"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ernie McMillan"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Care"
MATCH (b:ProperName)
WHERE b.Name = "Ernie McMillan"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Care"
MATCH (b:ProperName)
WHERE b.Name = "Magical Creatures"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professor Kettleburn"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Care"
MATCH (b:ProperName)
WHERE b.Name = "Professor Kettleburn"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Care"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Care"
MATCH (b:ProperName)
WHERE b.Name = "Those"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Careful"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Careful"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Careful"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cassandra Vablatsky"})
CREATE (:ProperName{ Name: "Future"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cassandra Vablatsky"
MATCH (b:ProperName)
WHERE b.Name = "Future"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Unfogging"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cassandra Vablatsky"
MATCH (b:ProperName)
WHERE b.Name = "Unfogging"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Diggory"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cedric Diggory"
MATCH (b:ProperName)
WHERE b.Name = "Diggory"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cedric Diggory"
MATCH (b:ProperName)
WHERE b.Name = "Seeker"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Certainly"})
CREATE (:ProperName{ Name: "Minerva"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Certainly"
MATCH (b:ProperName)
WHERE b.Name = "Minerva"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Change"})
CREATE (:ProperName{ Name: "Malfoy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Change"
MATCH (b:ProperName)
WHERE b.Name = "Malfoy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Change"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Charlie Weasley"})
CREATE (:ProperName{ Name: "Quidditch Cup"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Charlie Weasley"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch Cup"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Charm"})
CREATE (:ProperName{ Name: "Cure Reluctant Reversers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Charm"
MATCH (b:ProperName)
WHERE b.Name = "Cure Reluctant Reversers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Chaser"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Chaser"
MATCH (b:ProperName)
WHERE b.Name = "Gryffindor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Chaser"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Chasers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Chasers"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cho"})
CREATE (:ProperName{ Name: "Snitch"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cho"
MATCH (b:ProperName)
WHERE b.Name = "Snitch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Chocolate Frog"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Chocolate Frog"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Lupin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Chocolate Frog"
MATCH (b:ProperName)
WHERE b.Name = "Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Christmas Day"})
CREATE (:ProperName{ Name: "Most"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Christmas Day"
MATCH (b:ProperName)
WHERE b.Name = "Most"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Christmas"})
CREATE (:ProperName{ Name: "Easter"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Christmas"
MATCH (b:ProperName)
WHERE b.Name = "Easter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Had"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Christmas"
MATCH (b:ProperName)
WHERE b.Name = "Had"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Circumstances"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Circumstances"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cleansweeps"})
CREATE (:ProperName{ Name: "Silver Arrows"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cleansweeps"
MATCH (b:ProperName)
WHERE b.Name = "Silver Arrows"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cockroach Clusters"})
CREATE (:ProperName{ Name: "Hermione"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cockroach Clusters"
MATCH (b:ProperName)
WHERE b.Name = "Hermione"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cockroach Clusters"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Come"})
CREATE (:ProperName{ Name: "Miss"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Come"
MATCH (b:ProperName)
WHERE b.Name = "Miss"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Comet Two Sixty"})
CREATE (:ProperName{ Name: "On"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Comet Two Sixty"
MATCH (b:ProperName)
WHERE b.Name = "On"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Committee"
MATCH (b:ProperName)
WHERE b.Name = "Dangerous Creatures"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Committee"
MATCH (b:ProperName)
WHERE b.Name = "Disposal"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Confiscated"})
CREATE (:ProperName{ Name: "Highly Dangerous"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Confiscated"
MATCH (b:ProperName)
WHERE b.Name = "Highly Dangerous"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Confusing Concoction"})
CREATE (:ProperName{ Name: "Snape"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Confusing Concoction"
MATCH (b:ProperName)
WHERE b.Name = "Snape"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Congratulations"})
CREATE (:ProperName{ Name: "Hagrid"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Congratulations"
MATCH (b:ProperName)
WHERE b.Name = "Hagrid"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cornelius Fudge"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cornelius Fudge"
MATCH (b:ProperName)
WHERE b.Name = "Magic"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cornelius Fudge"
MATCH (b:ProperName)
WHERE b.Name = "Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Cornelius"})
CREATE (:ProperName{ Name: "You"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Cornelius"
MATCH (b:ProperName)
WHERE b.Name = "You"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Course"})
CREATE (:ProperName{ Name: "Pomfrey"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Course"
MATCH (b:ProperName)
WHERE b.Name = "Pomfrey"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Coyle"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Coyle"
MATCH (b:ProperName)
WHERE b.Name = "Crabbe"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Crabbe"
MATCH (b:ProperName)
WHERE b.Name = "Goyle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Crabbe"
MATCH (b:ProperName)
WHERE b.Name = "Malfoy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Crabbe"
MATCH (b:ProperName)
WHERE b.Name = "Marcus Flint"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Pansy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Crabbe"
MATCH (b:ProperName)
WHERE b.Name = "Pansy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Crookshanks"})
CREATE (:ProperName{ Name: "Seamus"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Crookshanks"
MATCH (b:ProperName)
WHERE b.Name = "Seamus"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "DIAMOND-HARD POLISH AND HAND"})
CREATE (:ProperName{ Name: "STATE-OF-THE-ART PACING BROOM SPORTS"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "DIAMOND-HARD POLISH AND HAND"
MATCH (b:ProperName)
WHERE b.Name = "STATE-OF-THE-ART PACING BROOM SPORTS"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "STREAM-LINED"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "DIAMOND-HARD POLISH AND HAND"
MATCH (b:ProperName)
WHERE b.Name = "STREAM-LINED"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "SUPERFINE HANDLE OF ASH"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "DIAMOND-HARD POLISH AND HAND"
MATCH (b:ProperName)
WHERE b.Name = "SUPERFINE HANDLE OF ASH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "TREATED WITH"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "DIAMOND-HARD POLISH AND HAND"
MATCH (b:ProperName)
WHERE b.Name = "TREATED WITH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "DON"})
CREATE (:ProperName{ Name: "YES"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "DON"
MATCH (b:ProperName)
WHERE b.Name = "YES"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dad"})
CREATE (:ProperName{ Name: "Daily Prophet Draw"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dad"
MATCH (b:ProperName)
WHERE b.Name = "Daily Prophet Draw"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dad"
MATCH (b:ProperName)
WHERE b.Name = "Mum"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "September"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dad"
MATCH (b:ProperName)
WHERE b.Name = "September"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Toothflossing Stringmints"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dad"
MATCH (b:ProperName)
WHERE b.Name = "Toothflossing Stringmints"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Daily Prophet Grand Prize Galleon Draw"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Daily Prophet Grand Prize Galleon Draw"
MATCH (b:ProperName)
WHERE b.Name = "Magic"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ministry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Daily Prophet Grand Prize Galleon Draw"
MATCH (b:ProperName)
WHERE b.Name = "Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dangerous Creatures"
MATCH (b:ProperName)
WHERE b.Name = "Disposal"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Defense Against"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dark Arts"
MATCH (b:ProperName)
WHERE b.Name = "Defense Against"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dark Magic"})
CREATE (:ProperName{ Name: "Full"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dark Magic"
MATCH (b:ProperName)
WHERE b.Name = "Full"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "This"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dark Magic"
MATCH (b:ProperName)
WHERE b.Name = "This"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dark Side"})
CREATE (:ProperName{ Name: "Sirius Black"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dark Side"
MATCH (b:ProperName)
WHERE b.Name = "Sirius Black"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Davies"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Davies"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Death Omens"
MATCH (b:ProperName)
WHERE b.Name = "Flourish"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Decree"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Decree"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Restriction"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Decree"
MATCH (b:ProperName)
WHERE b.Name = "Restriction"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Underage Wizardry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Decree"
MATCH (b:ProperName)
WHERE b.Name = "Underage Wizardry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dementor"})
CREATE (:ProperName{ Name: "They"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dementor"
MATCH (b:ProperName)
WHERE b.Name = "They"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Department"})
CREATE (:ProperName{ Name: "Junior Minister"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Department"
MATCH (b:ProperName)
WHERE b.Name = "Junior Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Magical Catastrophes"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Department"
MATCH (b:ProperName)
WHERE b.Name = "Magical Catastrophes"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Slytherin Beater"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Derrick"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin Beater"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dervish"
MATCH (b:ProperName)
WHERE b.Name = "They"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Detention"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Detention"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Diagon Alley"})
CREATE (:ProperName{ Name: "Muggle London"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Diagon Alley"
MATCH (b:ProperName)
WHERE b.Name = "Muggle London"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sibyll Trelawney"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Divination"
MATCH (b:ProperName)
WHERE b.Name = "Sibyll Trelawney"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Divination"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Do When You Know"})
CREATE (:ProperName{ Name: "What"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Do When You Know"
MATCH (b:ProperName)
WHERE b.Name = "What"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Worst Is Coming"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Do When You Know"
MATCH (b:ProperName)
WHERE b.Name = "Worst Is Coming"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Do-It-Yourself Broomcare"
MATCH (b:ProperName)
WHERE b.Name = "Handbook"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Draco"})
CREATE (:ProperName{ Name: "How"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Draco"
MATCH (b:ProperName)
WHERE b.Name = "How"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dumbledore"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "James Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Passing"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "Passing"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sprout"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "Sprout"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dungbomb"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbomb"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "We"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbomb"
MATCH (b:ProperName)
WHERE b.Name = "We"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dungbombs"})
CREATE (:ProperName{ Name: "Frog Spawn Soap"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbombs"
MATCH (b:ProperName)
WHERE b.Name = "Frog Spawn Soap"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbombs"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hiccup Sweets"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbombs"
MATCH (b:ProperName)
WHERE b.Name = "Hiccup Sweets"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Nose-Biting Teacup"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dungbombs"
MATCH (b:ProperName)
WHERE b.Name = "Nose-Biting Teacup"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Dursley"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Dursley"
MATCH (b:ProperName)
WHERE b.Name = "Privet Drive"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "EXPECTO PATRONUM"})
CREATE (:ProperName{ Name: "PATRONUM"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "EXPECTO PATRONUM"
MATCH (b:ProperName)
WHERE b.Name = "PATRONUM"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Early Christmas"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Early Christmas"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Easter"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "End"})
CREATE (:ProperName{ Name: "October"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "End"
MATCH (b:ProperName)
WHERE b.Name = "October"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Enjoy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Enjoy"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ere"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ere"
MATCH (b:ProperName)
WHERE b.Name = "Madam Marsh"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ern"})
CREATE (:ProperName{ Name: "Ernie Prang"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ern"
MATCH (b:ProperName)
WHERE b.Name = "Ernie Prang"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wales"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ern"
MATCH (b:ProperName)
WHERE b.Name = "Wales"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ernie McMillan"
MATCH (b:ProperName)
WHERE b.Name = "Magical Creatures"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Neville Longbottom"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ernie Prang"
MATCH (b:ProperName)
WHERE b.Name = "Neville Longbottom"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ernie Prang"
MATCH (b:ProperName)
WHERE b.Name = "This"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Even"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Even"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Every Flavor Beans"})
CREATE (:ProperName{ Name: "Fizzing Whizbees"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Every Flavor Beans"
MATCH (b:ProperName)
WHERE b.Name = "Fizzing Whizbees"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Everybody"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Everybody"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "You-Know-Who"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Everybody"
MATCH (b:ProperName)
WHERE b.Name = "You-Know-Who"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Expecto"})
CREATE (:ProperName{ Name: "Pat"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Expecto"
MATCH (b:ProperName)
WHERE b.Name = "Pat"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Explain"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Explain"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Exploding Snap"})
CREATE (:ProperName{ Name: "Want"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Exploding Snap"
MATCH (b:ProperName)
WHERE b.Name = "Want"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "FIREBOLT HAS AN ACCELERATION OF"})
CREATE (:ProperName{ Name: "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FIREBOLT HAS AN ACCELERATION OF"
MATCH (b:ProperName)
WHERE b.Name = "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FIREBOLT HAS AN ACCELERATION OF"
MATCH (b:ProperName)
WHERE b.Name = "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FIREBOLT HAS AN ACCELERATION OF"
MATCH (b:ProperName)
WHERE b.Name = "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "NUMBERED WITH ITS OWN REGISTRATION NUMBER"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FIREBOLT HAS AN ACCELERATION OF"
MATCH (b:ProperName)
WHERE b.Name = "NUMBERED WITH ITS OWN REGISTRATION NUMBER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "ON REQUEST"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FIREBOLT HAS AN ACCELERATION OF"
MATCH (b:ProperName)
WHERE b.Name = "ON REQUEST"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "FOR ME IN THE ENTRANCE HALL"})
CREATE (:ProperName{ Name: "YOU"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "FOR ME IN THE ENTRANCE HALL"
MATCH (b:ProperName)
WHERE b.Name = "YOU"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Face"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Face"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Fang"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fang"
MATCH (b:ProperName)
WHERE b.Name = "Hagrid"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Fat Lady"})
CREATE (:ProperName{ Name: "Frightened"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fat Lady"
MATCH (b:ProperName)
WHERE b.Name = "Frightened"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Father"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Father"
MATCH (b:ProperName)
WHERE b.Name = "Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Why"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Father"
MATCH (b:ProperName)
WHERE b.Name = "Why"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Filch"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Filch"
MATCH (b:ProperName)
WHERE b.Name = "Sprout"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Firebolt"})
CREATE (:ProperName{ Name: "First"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Firebolt"
MATCH (b:ProperName)
WHERE b.Name = "First"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gringotts"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Firebolt"
MATCH (b:ProperName)
WHERE b.Name = "Gringotts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Including"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Firebolt"
MATCH (b:ProperName)
WHERE b.Name = "Including"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Passed"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Firebolt"
MATCH (b:ProperName)
WHERE b.Name = "Passed"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Which Broomstick"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Firebolt"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "First Class"})
CREATE (:ProperName{ Name: "Merlin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "First Class"
MATCH (b:ProperName)
WHERE b.Name = "Merlin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Order"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "First Class"
MATCH (b:ProperName)
WHERE b.Name = "Order"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Pettigrew"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "First Class"
MATCH (b:ProperName)
WHERE b.Name = "Pettigrew"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professor Lupin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "First"
MATCH (b:ProperName)
WHERE b.Name = "Professor Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Scabbers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "First"
MATCH (b:ProperName)
WHERE b.Name = "Scabbers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fisheries"
MATCH (b:ProperName)
WHERE b.Name = "The Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Five"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Five"
MATCH (b:ProperName)
WHERE b.Name = "Gryffindor"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fizzing Whizbees"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fizzing Whizbees"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Seen"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fizzing Whizbees"
MATCH (b:ProperName)
WHERE b.Name = "Seen"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Flitwick"})
CREATE (:ProperName{ Name: "McGonagall"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Flitwick"
MATCH (b:ProperName)
WHERE b.Name = "McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professors McGonagall"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Flitwick"
MATCH (b:ProperName)
WHERE b.Name = "Professors McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Flitwick"
MATCH (b:ProperName)
WHERE b.Name = "Sprout"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Florean Fortescue"})
CREATE (:ProperName{ Name: "Wednesday"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Florean Fortescue"
MATCH (b:ProperName)
WHERE b.Name = "Wednesday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Flourish"
MATCH (b:ProperName)
WHERE b.Name = "Madam Malkin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Uncle Vernon"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "For"
MATCH (b:ProperName)
WHERE b.Name = "Uncle Vernon"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Forget"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Forget"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Forward"})
CREATE (:ProperName{ Name: "Neville"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Forward"
MATCH (b:ProperName)
WHERE b.Name = "Neville"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Foul"})
CREATE (:ProperName{ Name: "Fowl"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Foul"
MATCH (b:ProperName)
WHERE b.Name = "Fowl"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hippogriff Brutality"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Foul"
MATCH (b:ProperName)
WHERE b.Name = "Hippogriff Brutality"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hippogriff Psychology"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Foul"
MATCH (b:ProperName)
WHERE b.Name = "Hippogriff Psychology"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Foul"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "The Handbook"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Foul"
MATCH (b:ProperName)
WHERE b.Name = "The Handbook"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Fourteenth Century Was Completely Pointless"})
CREATE (:ProperName{ Name: "Witch Burning"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fourteenth Century Was Completely Pointless"
MATCH (b:ProperName)
WHERE b.Name = "Witch Burning"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fowl"
MATCH (b:ProperName)
WHERE b.Name = "Hippogriff Brutality"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fowl"
MATCH (b:ProperName)
WHERE b.Name = "Hippogriff Psychology"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fowl"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fowl"
MATCH (b:ProperName)
WHERE b.Name = "The Handbook"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Warrington"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fred Weasley"
MATCH (b:ProperName)
WHERE b.Name = "Warrington"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Fred"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fred"
MATCH (b:ProperName)
WHERE b.Name = "George"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "George Weasley"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Fred"
MATCH (b:ProperName)
WHERE b.Name = "George Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Friday"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Friday"
MATCH (b:ProperName)
WHERE b.Name = "October"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Frog Spawn Soap"
MATCH (b:ProperName)
WHERE b.Name = "Hiccup Sweets"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Frog Spawn Soap"
MATCH (b:ProperName)
WHERE b.Name = "Nose-Biting Teacup"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Frog"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Frog"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Future"
MATCH (b:ProperName)
WHERE b.Name = "Unfogging"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "GENTLEMAN"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GENTLEMAN"
MATCH (b:ProperName)
WHERE b.Name = "HARRY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "THIS IS NO TIME TO BE"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GENTLEMAN"
MATCH (b:ProperName)
WHERE b.Name = "THIS IS NO TIME TO BE"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "GET OFF"})
CREATE (:ProperName{ Name: "YOU STUPID ANIMAL"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GET OFF"
MATCH (b:ProperName)
WHERE b.Name = "YOU STUPID ANIMAL"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"
MATCH (b:ProperName)
WHERE b.Name = "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"
MATCH (b:ProperName)
WHERE b.Name = "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"
MATCH (b:ProperName)
WHERE b.Name = "NUMBERED WITH ITS OWN REGISTRATION NUMBER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GIVING THE FIREBOLT UNSURPASSABLE BALANCE AND PINPOINT PRECISION"
MATCH (b:ProperName)
WHERE b.Name = "ON REQUEST"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "GONE"})
CREATE (:ProperName{ Name: "YOU KNOW WHAT WAS ON THE FLOOR"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "GONE"
MATCH (b:ProperName)
WHERE b.Name = "YOU KNOW WHAT WAS ON THE FLOOR"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Galleons"})
CREATE (:ProperName{ Name: "Knuts"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Galleons"
MATCH (b:ProperName)
WHERE b.Name = "Knuts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sickles"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Galleons"
MATCH (b:ProperName)
WHERE b.Name = "Sickles"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "George"
MATCH (b:ProperName)
WHERE b.Name = "Peppermint Toads"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gift"})
CREATE (:ProperName{ Name: "It"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gift"
MATCH (b:ProperName)
WHERE b.Name = "It"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Girl"})
CREATE (:ProperName{ Name: "Head Boy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Girl"
MATCH (b:ProperName)
WHERE b.Name = "Head Boy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Give Harry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Give Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hagrid"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Good"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Good"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Goyle"
MATCH (b:ProperName)
WHERE b.Name = "Marcus Flint"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Goyle"
MATCH (b:ProperName)
WHERE b.Name = "Pansy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Grade Three"})
CREATE (:ProperName{ Name: "Spells"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Grade Three"
MATCH (b:ProperName)
WHERE b.Name = "Spells"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "The Standard Book"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Grade Three"
MATCH (b:ProperName)
WHERE b.Name = "The Standard Book"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gramatica"})
CREATE (:ProperName{ Name: "Numerology"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gramatica"
MATCH (b:ProperName)
WHERE b.Name = "Numerology"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Great Grays"})
CREATE (:ProperName{ Name: "Scops"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Great Grays"
MATCH (b:ProperName)
WHERE b.Name = "Scops"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Grim"})
CREATE (:ProperName{ Name: "The Grim"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Grim"
MATCH (b:ProperName)
WHERE b.Name = "The Grim"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "London"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gringotts Wizarding Bank"
MATCH (b:ProperName)
WHERE b.Name = "London"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gringotts"
MATCH (b:ProperName)
WHERE b.Name = "Knuts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gryffindor House"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor House"
MATCH (b:ProperName)
WHERE b.Name = "McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Transfiguration"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor House"
MATCH (b:ProperName)
WHERE b.Name = "Transfiguration"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gryffindor Tower"})
CREATE (:ProperName{ Name: "New Year"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor Tower"
MATCH (b:ProperName)
WHERE b.Name = "New Year"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Gryffindor-Slytherin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor-Slytherin"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Johnson"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Katie Bell"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Nearly Headless Nick"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Nearly Headless Nick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "O1iver Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Penalty"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Penalty"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sunday"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Sunday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Gryffindor"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HARRY"
MATCH (b:ProperName)
WHERE b.Name = "THIS IS NO TIME TO BE"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HARRY"
MATCH (b:ProperName)
WHERE b.Name = "YOU TWO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "HELLO"})
CREATE (:ProperName{ Name: "YOU HEAR ME"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HELLO"
MATCH (b:ProperName)
WHERE b.Name = "YOU HEAR ME"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HOLDING"
MATCH (b:ProperName)
WHERE b.Name = "KNIFE"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HOLDING"
MATCH (b:ProperName)
WHERE b.Name = "PROFESSOR"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "HOLDING"
MATCH (b:ProperName)
WHERE b.Name = "WOKE UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "January"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagrid"
MATCH (b:ProperName)
WHERE b.Name = "January"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Plastered"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagrid"
MATCH (b:ProperName)
WHERE b.Name = "Plastered"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "RE NOT ALLOWED OUT ON YOUR OWN"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagrid"
MATCH (b:ProperName)
WHERE b.Name = "RE NOT ALLOWED OUT ON YOUR OWN"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagrid"
MATCH (b:ProperName)
WHERE b.Name = "Seen"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "To"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagrid"
MATCH (b:ProperName)
WHERE b.Name = "To"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hagridsized"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hagridsized"
MATCH (b:ProperName)
WHERE b.Name = "Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Handbook"
MATCH (b:ProperName)
WHERE b.Name = "Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hannah Abbott"})
CREATE (:ProperName{ Name: "Hufflepuff"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hannah Abbott"
MATCH (b:ProperName)
WHERE b.Name = "Hufflepuff"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Harry Potter"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry Potter"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Harry UP"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry UP"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hello"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hello"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Herbology"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Herbology"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Herinione"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Herinione"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hermlone"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hermlone"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hey"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hey"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hogwarts House"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts House"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "How Abut"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "How Abut"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Lily"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Lily"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Magical Mischief Makers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Magical Mischief Makers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Not Harry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Not Harry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "November"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "November"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Oooh"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Oooh"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Picked"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Picked"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Pink"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Pink"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Pomfrey"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Privet Drive"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Put"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Put"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Ravenclaw Beaters"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Remember"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Remember"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Seen"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Show"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Show"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Split"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Split"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ugh"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Ugh"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Undetectable Poisons"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Undetectable Poisons"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wait"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Wait"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Weasleys"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Weasleys"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Wednesday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Harry"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hat"})
CREATE (:ProperName{ Name: "House"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hat"
MATCH (b:ProperName)
WHERE b.Name = "House"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Houses"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hat"
MATCH (b:ProperName)
WHERE b.Name = "Houses"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "He"})
CREATE (:ProperName{ Name: "Mount Your"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "He"
MATCH (b:ProperName)
WHERE b.Name = "Mount Your"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Head"})
CREATE (:ProperName{ Name: "Misuse"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Head"
MATCH (b:ProperName)
WHERE b.Name = "Misuse"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Muggle Artifacts Office"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Head"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Artifacts Office"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Head"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Heard"})
CREATE (:ProperName{ Name: "Marge"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Heard"
MATCH (b:ProperName)
WHERE b.Name = "Marge"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hedwig"})
CREATE (:ProperName{ Name: "Hermes"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hedwig"
MATCH (b:ProperName)
WHERE b.Name = "Hermes"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Owlery"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hedwig"
MATCH (b:ProperName)
WHERE b.Name = "Owlery"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hello"
MATCH (b:ProperName)
WHERE b.Name = "Percy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Her"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Her"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Herbology"
MATCH (b:ProperName)
WHERE b.Name = "Hermione"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Herbology"
MATCH (b:ProperName)
WHERE b.Name = "Hufflepuff"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermes"
MATCH (b:ProperName)
WHERE b.Name = "Percy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hermione Granger"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione Granger"
MATCH (b:ProperName)
WHERE b.Name = "Hogwarts"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Mobiliarbus"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione"
MATCH (b:ProperName)
WHERE b.Name = "Mobiliarbus"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Peppermint Toad"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione"
MATCH (b:ProperName)
WHERE b.Name = "Peppermint Toad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione"
MATCH (b:ProperName)
WHERE b.Name = "Put"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Some"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione"
MATCH (b:ProperName)
WHERE b.Name = "Some"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wow"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermione"
MATCH (b:ProperName)
WHERE b.Name = "Wow"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hermlone"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hero-worshipped Black"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hero-worshipped Black"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hey"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hi"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hi"
MATCH (b:ProperName)
WHERE b.Name = "Neville"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hiccup Sweets"
MATCH (b:ProperName)
WHERE b.Name = "Nose-Biting Teacup"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "High-Finish Handle Polish"})
CREATE (:ProperName{ Name: "Tall-Twig Clippers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "High-Finish Handle Polish"
MATCH (b:ProperName)
WHERE b.Name = "Tall-Twig Clippers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hippogriff Brutality"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hippogriff Psychology"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hippogriff Psychology"
MATCH (b:ProperName)
WHERE b.Name = "The Handbook"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Historical Sorcery"})
CREATE (:ProperName{ Name: "In Sites"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Historical Sorcery"
MATCH (b:ProperName)
WHERE b.Name = "In Sites"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "History"
MATCH (b:ProperName)
WHERE b.Name = "Magic"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Thursday"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "History"
MATCH (b:ProperName)
WHERE b.Name = "Thursday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "History"
MATCH (b:ProperName)
WHERE b.Name = "Wednesday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hit Wizards"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hit Wizards"
MATCH (b:ProperName)
WHERE b.Name = "Magical Law Enforcement Squad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Nobody"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hit Wizards"
MATCH (b:ProperName)
WHERE b.Name = "Nobody"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hog"})
CREATE (:ProperName{ Name: "Third"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hog"
MATCH (b:ProperName)
WHERE b.Name = "Third"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hogsmeade"})
CREATE (:ProperName{ Name: "Think"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hogsmeade"
MATCH (b:ProperName)
WHERE b.Name = "Think"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hogwarts Express"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hogwarts Express"
MATCH (b:ProperName)
WHERE b.Name = "September"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hogwarts School"})
CREATE (:ProperName{ Name: "Witchcraft"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hogwarts School"
MATCH (b:ProperName)
WHERE b.Name = "Witchcraft"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wizardry"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hogwarts School"
MATCH (b:ProperName)
WHERE b.Name = "Wizardry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hogwarts"
MATCH (b:ProperName)
WHERE b.Name = "Houses"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Home Life"
MATCH (b:ProperName)
WHERE b.Name = "Social Habits"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Honeydukes"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Honeydukes"
MATCH (b:ProperName)
WHERE b.Name = "Toothflossing Stringmints"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "How Abut"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ravenclaw"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hufflepuff"
MATCH (b:ProperName)
WHERE b.Name = "Ravenclaw"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Hullo"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Hullo"
MATCH (b:ProperName)
WHERE b.Name = "Neville"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"
MATCH (b:ProperName)
WHERE b.Name = "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"
MATCH (b:ProperName)
WHERE b.Name = "NUMBERED WITH ITS OWN REGISTRATION NUMBER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "INDIVIDUALLY SELECTED BIRCH TWIG IN THE BROOMTAIL HAS BEEN HONED TO AERODYNAMIC PERFECTION"
MATCH (b:ProperName)
WHERE b.Name = "ON REQUEST"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "If"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "If"
MATCH (b:ProperName)
WHERE b.Name = "Minerva"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Incurably Criminal Boys"})
CREATE (:ProperName{ Name: "Secure Center"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Incurably Criminal Boys"
MATCH (b:ProperName)
WHERE b.Name = "Secure Center"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Inner Eye"})
CREATE (:ProperName{ Name: "Signs"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Inner Eye"
MATCH (b:ProperName)
WHERE b.Name = "Signs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Insulate Yourself Against Shocks"
MATCH (b:ProperName)
WHERE b.Name = "Predicting"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Insulate Yourself Against Shocks"
MATCH (b:ProperName)
WHERE b.Name = "Unpredictable"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Insulate Yourself Against Shocks"
MATCH (b:ProperName)
WHERE b.Name = "When Fortunes Turn Foul"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "International Federation"})
CREATE (:ProperName{ Name: "Muggle Prime Minister"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "International Federation"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Prime Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Warlocks"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "International Federation"
MATCH (b:ProperName)
WHERE b.Name = "Warlocks"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Invisibility"})
CREATE (:ProperName{ Name: "Invisible Book"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Invisibility"
MATCH (b:ProperName)
WHERE b.Name = "Invisible Book"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "My Lord"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "It"
MATCH (b:ProperName)
WHERE b.Name = "My Lord"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Poppy"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "It"
MATCH (b:ProperName)
WHERE b.Name = "Poppy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "JORDAN"})
CREATE (:ProperName{ Name: "ON WITH THE COMMENTARY"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "JORDAN"
MATCH (b:ProperName)
WHERE b.Name = "ON WITH THE COMMENTARY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "YOU BEING PAID TO ADVERTISE FIREBOLTS"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "JORDAN"
MATCH (b:ProperName)
WHERE b.Name = "YOU BEING PAID TO ADVERTISE FIREBOLTS"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "James Potter"
MATCH (b:ProperName)
WHERE b.Name = "Lily"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "James"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "James"
MATCH (b:ProperName)
WHERE b.Name = "Lily"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sirius"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "James"
MATCH (b:ProperName)
WHERE b.Name = "Sirius"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Spinnet"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Johnson"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Joke Shop"})
CREATE (:ProperName{ Name: "Three Broomsticks"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Joke Shop"
MATCH (b:ProperName)
WHERE b.Name = "Three Broomsticks"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "June"})
CREATE (:ProperName{ Name: "Orb"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "June"
MATCH (b:ProperName)
WHERE b.Name = "Orb"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Junior Minister"
MATCH (b:ProperName)
WHERE b.Name = "Magical Catastrophes"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "KNIFE"
MATCH (b:ProperName)
WHERE b.Name = "PROFESSOR"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "KNIFE"
MATCH (b:ProperName)
WHERE b.Name = "WOKE UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "KNOW"})
CREATE (:ProperName{ Name: "OLIVER"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "KNOW"
MATCH (b:ProperName)
WHERE b.Name = "OLIVER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Katie Bell"
MATCH (b:ProperName)
WHERE b.Name = "Quaffle"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Katie"})
CREATE (:ProperName{ Name: "Slytherin Chaser"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Katie"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin Chaser"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Slytherin Seeker"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Katie"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin Seeker"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Keep"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Keep"
MATCH (b:ProperName)
WHERE b.Name = "Malfoy"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Keeper"})
CREATE (:ProperName{ Name: "Spanking"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Keeper"
MATCH (b:ProperName)
WHERE b.Name = "Spanking"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Knuts"
MATCH (b:ProperName)
WHERE b.Name = "Sickles"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Lavender Brown"})
CREATE (:ProperName{ Name: "Patil"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lavender Brown"
MATCH (b:ProperName)
WHERE b.Name = "Patil"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Leave"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Leave"
MATCH (b:ProperName)
WHERE b.Name = "Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Lee Jordan"})
CREATE (:ProperName{ Name: "Slytherin Beaters"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lee Jordan"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin Beaters"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Lee"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lee"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lily"
MATCH (b:ProperName)
WHERE b.Name = "Sirius"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Longbottom"})
CREATE (:ProperName{ Name: "Orange"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Longbottom"
MATCH (b:ProperName)
WHERE b.Name = "Orange"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Longbottorn"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Longbottorn"
MATCH (b:ProperName)
WHERE b.Name = "Potter"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Longbottorn"
MATCH (b:ProperName)
WHERE b.Name = "You"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Loony"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Loony"
MATCH (b:ProperName)
WHERE b.Name = "Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Mongolia"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lupin"
MATCH (b:ProperName)
WHERE b.Name = "Mongolia"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Lupin"
MATCH (b:ProperName)
WHERE b.Name = "Professors McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"
MATCH (b:ProperName)
WHERE b.Name = "NUMBERED WITH ITS OWN REGISTRATION NUMBER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "MILES AN HOUR IN TEN SECONDS AND INCORPORATES AN UNBREAKABLE BRAKING CHARM"
MATCH (b:ProperName)
WHERE b.Name = "ON REQUEST"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Madam Marsh"
MATCH (b:ProperName)
WHERE b.Name = "Stan"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "Misuse"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Artifacts Office"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "The Ministry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magic"
MATCH (b:ProperName)
WHERE b.Name = "Wednesday"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magical Creatures"
MATCH (b:ProperName)
WHERE b.Name = "Professor Kettleburn"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magical Creatures"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magical Law Enforcement Squad"
MATCH (b:ProperName)
WHERE b.Name = "Nobody"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Magical Mischief-Makers"
MATCH (b:ProperName)
WHERE b.Name = "THE MARAUDER"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Malfay"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfay"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoy"
MATCH (b:ProperName)
WHERE b.Name = "Marcus Flint"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Shove"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoy"
MATCH (b:ProperName)
WHERE b.Name = "Shove"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Shut"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoy"
MATCH (b:ProperName)
WHERE b.Name = "Shut"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Was Professor Flitwick"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoy"
MATCH (b:ProperName)
WHERE b.Name = "Was Professor Flitwick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "She"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoys"
MATCH (b:ProperName)
WHERE b.Name = "She"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Voldemort"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Malfoys"
MATCH (b:ProperName)
WHERE b.Name = "Voldemort"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Many"})
CREATE (:ProperName{ Name: "Severus"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Many"
MATCH (b:ProperName)
WHERE b.Name = "Severus"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Marcus Flint"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Tea"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Marge"
MATCH (b:ProperName)
WHERE b.Name = "Tea"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professors Snape"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "McGonagall"
MATCH (b:ProperName)
WHERE b.Name = "Professors Snape"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "McGonagall"
MATCH (b:ProperName)
WHERE b.Name = "Sprout"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Merlin"
MATCH (b:ProperName)
WHERE b.Name = "Order"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Merlin"
MATCH (b:ProperName)
WHERE b.Name = "Pettigrew"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Squad"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Merlin"
MATCH (b:ProperName)
WHERE b.Name = "Squad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Messrs"})
CREATE (:ProperName{ Name: "Padfoot"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Messrs"
MATCH (b:ProperName)
WHERE b.Name = "Padfoot"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Prongs"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Messrs"
MATCH (b:ProperName)
WHERE b.Name = "Prongs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wormtail"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Messrs"
MATCH (b:ProperName)
WHERE b.Name = "Wormtail"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Minerva"
MATCH (b:ProperName)
WHERE b.Name = "Professor Lupin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "There"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Minerva"
MATCH (b:ProperName)
WHERE b.Name = "There"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ministry"
MATCH (b:ProperName)
WHERE b.Name = "Misuse"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ministry"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Artifacts Office"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ministry"
MATCH (b:ProperName)
WHERE b.Name = "Underage Wizardry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Misuse"
MATCH (b:ProperName)
WHERE b.Name = "Muggle Artifacts Office"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Misuse"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Monster Book"})
CREATE (:ProperName{ Name: "Monsters"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Monster Book"
MATCH (b:ProperName)
WHERE b.Name = "Monsters"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Monster Books"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Monster Books"
MATCH (b:ProperName)
WHERE b.Name = "What"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "The Monster Book"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Monsters"
MATCH (b:ProperName)
WHERE b.Name = "The Monster Book"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Moony"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Moony"
MATCH (b:ProperName)
WHERE b.Name = "Padfoot"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Moony"
MATCH (b:ProperName)
WHERE b.Name = "Prongs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "With"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Moony"
MATCH (b:ProperName)
WHERE b.Name = "With"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Moony"
MATCH (b:ProperName)
WHERE b.Name = "Wormtail"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Wormtaill Padfoot"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Moony"
MATCH (b:ProperName)
WHERE b.Name = "Wormtaill Padfoot"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Move"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Move"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Mr"})
CREATE (:ProperName{ Name: "Mrs"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Mr"
MATCH (b:ProperName)
WHERE b.Name = "Mrs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Muggle Artifacts Office"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Muggle Prime Minister"
MATCH (b:ProperName)
WHERE b.Name = "Warlocks"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Muggle Studies"
MATCH (b:ProperName)
WHERE b.Name = "Study"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Prime Minister"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Muggle"
MATCH (b:ProperName)
WHERE b.Name = "Prime Minister"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Mum"
MATCH (b:ProperName)
WHERE b.Name = "September"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Mum"
MATCH (b:ProperName)
WHERE b.Name = "Toothflossing Stringmints"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Potters"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "My Lord"
MATCH (b:ProperName)
WHERE b.Name = "Potters"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Secret-Keeper"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "My Lord"
MATCH (b:ProperName)
WHERE b.Name = "Secret-Keeper"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "NO"
MATCH (b:ProperName)
WHERE b.Name = "NO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Necessary"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Necessary"
MATCH (b:ProperName)
WHERE b.Name = "YOU"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Run"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Neville"
MATCH (b:ProperName)
WHERE b.Name = "Run"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Nim"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Nim"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Two Thousand"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Nim"
MATCH (b:ProperName)
WHERE b.Name = "Two Thousand"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Nimbus Two Thousand"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Nimbus Two Thousand"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "No Way"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "No Way"
MATCH (b:ProperName)
WHERE b.Name = "Ravenclaw"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "No Way"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "None"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "None"
MATCH (b:ProperName)
WHERE b.Name = "Sirius Black"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "November"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Now"})
CREATE (:ProperName{ Name: "Penny"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Now"
MATCH (b:ProperName)
WHERE b.Name = "Penny"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "O1iver Wood"
MATCH (b:ProperName)
WHERE b.Name = "Quidditch"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "ON WITH THE COMMENTARY"
MATCH (b:ProperName)
WHERE b.Name = "YOU BEING PAID TO ADVERTISE FIREBOLTS"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Oh"})
CREATE (:ProperName{ Name: "Professorhead"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Oh"
MATCH (b:ProperName)
WHERE b.Name = "Professorhead"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Oliver"})
CREATE (:ProperName{ Name: "Stop"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Oliver"
MATCH (b:ProperName)
WHERE b.Name = "Stop"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "One"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "One"
MATCH (b:ProperName)
WHERE b.Name = "Which Broomstick"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "See"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Orb"
MATCH (b:ProperName)
WHERE b.Name = "See"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Order"
MATCH (b:ProperName)
WHERE b.Name = "Pettigrew"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Order"
MATCH (b:ProperName)
WHERE b.Name = "Squad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "PROFESSOR"
MATCH (b:ProperName)
WHERE b.Name = "WOKE UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Padfoot"
MATCH (b:ProperName)
WHERE b.Name = "Prongs"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Padfoot"
MATCH (b:ProperName)
WHERE b.Name = "With"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Padfoot"
MATCH (b:ProperName)
WHERE b.Name = "Wormtail"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Pansy Parkinson"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Pansy Parkinson"
MATCH (b:ProperName)
WHERE b.Name = "Slytherin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professor Trelawney"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Patil"
MATCH (b:ProperName)
WHERE b.Name = "Professor Trelawney"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Patronus Charm"})
CREATE (:ProperName{ Name: "Wizarding Level"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Patronus Charm"
MATCH (b:ProperName)
WHERE b.Name = "Wizarding Level"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Peeves"})
CREATE (:ProperName{ Name: "Poltergeist"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Peeves"
MATCH (b:ProperName)
WHERE b.Name = "Poltergeist"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Penelope"})
CREATE (:ProperName{ Name: "Ten Galleons"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Penelope"
MATCH (b:ProperName)
WHERE b.Name = "Ten Galleons"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Pepper Imps"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Pepper Imps"
MATCH (b:ProperName)
WHERE b.Name = "Toothflossing Stringmints"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Percy"
MATCH (b:ProperName)
WHERE b.Name = "Pink"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Peter Pettigrew"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Peter Pettigrew"
MATCH (b:ProperName)
WHERE b.Name = "Sirius Black"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Pettigrew"
MATCH (b:ProperName)
WHERE b.Name = "Squad"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Place"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Place"
MATCH (b:ProperName)
WHERE b.Name = "Seeker"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Points"})
CREATE (:ProperName{ Name: "SCORES"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Points"
MATCH (b:ProperName)
WHERE b.Name = "SCORES"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "SHE SCORES"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Points"
MATCH (b:ProperName)
WHERE b.Name = "SHE SCORES"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Portrait"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Portrait"
MATCH (b:ProperName)
WHERE b.Name = "Professor McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Portrait"
MATCH (b:ProperName)
WHERE b.Name = "Ron"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Potions"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potions"
MATCH (b:ProperName)
WHERE b.Name = "Remember"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Prisoner"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Sibyll Trelawney"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Spinnet"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Staying"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Staying"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sure"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Sure"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Turn"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potter"
MATCH (b:ProperName)
WHERE b.Name = "Turn"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "So Black"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potters"
MATCH (b:ProperName)
WHERE b.Name = "So Black"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Potty"})
CREATE (:ProperName{ Name: "Weasel"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Potty"
MATCH (b:ProperName)
WHERE b.Name = "Weasel"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Predicting"
MATCH (b:ProperName)
WHERE b.Name = "Unpredictable"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Predicting"
MATCH (b:ProperName)
WHERE b.Name = "When Fortunes Turn Foul"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Professor Dumbledore"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Professor Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "Professors McGonagall"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Somebody"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Professor Dumbledore"
MATCH (b:ProperName)
WHERE b.Name = "Somebody"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Seers"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Professor Trelawney"
MATCH (b:ProperName)
WHERE b.Name = "Seers"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Professors McGonagall"
MATCH (b:ProperName)
WHERE b.Name = "Snape"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Trelawney"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Professors Snape"
MATCH (b:ProperName)
WHERE b.Name = "Trelawney"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Prongs"
MATCH (b:ProperName)
WHERE b.Name = "Wormtail"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Prongs"
MATCH (b:ProperName)
WHERE b.Name = "Wormtaill Padfoot"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Quaffle Out"
MATCH (b:ProperName)
WHERE b.Name = "Warrington"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Quaffle"
MATCH (b:ProperName)
WHERE b.Name = "Warrington"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Quidditch Cup-winners"})
CREATE (:ProperName{ Name: "Rules"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Quidditch Cup-winners"
MATCH (b:ProperName)
WHERE b.Name = "Rules"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Quidditch"
MATCH (b:ProperName)
WHERE b.Name = "Two Thousand"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Ravenclaw Captain"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ravenclaw Captain"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Shooting Star"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ravenclaw"
MATCH (b:ProperName)
WHERE b.Name = "Shooting Star"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "The Decree"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Restriction"
MATCH (b:ProperName)
WHERE b.Name = "The Decree"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Restriction"
MATCH (b:ProperName)
WHERE b.Name = "Underage Wizardry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "UP"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Ron"
MATCH (b:ProperName)
WHERE b.Name = "UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Rosmerta"})
CREATE (:ProperName{ Name: "Ta"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Rosmerta"
MATCH (b:ProperName)
WHERE b.Name = "Ta"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "SCORES"
MATCH (b:ProperName)
WHERE b.Name = "SHE SCORES"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "STATE-OF-THE-ART PACING BROOM SPORTS"
MATCH (b:ProperName)
WHERE b.Name = "STREAM-LINED"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "STATE-OF-THE-ART PACING BROOM SPORTS"
MATCH (b:ProperName)
WHERE b.Name = "SUPERFINE HANDLE OF ASH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "STATE-OF-THE-ART PACING BROOM SPORTS"
MATCH (b:ProperName)
WHERE b.Name = "TREATED WITH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "STREAM-LINED"
MATCH (b:ProperName)
WHERE b.Name = "SUPERFINE HANDLE OF ASH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "STREAM-LINED"
MATCH (b:ProperName)
WHERE b.Name = "TREATED WITH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "SUPERFINE HANDLE OF ASH"
MATCH (b:ProperName)
WHERE b.Name = "TREATED WITH"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Then"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Sibyll Trelawney"
MATCH (b:ProperName)
WHERE b.Name = "Then"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Sibyll"})
CREATE (:ProperName{ Name: "Tripe"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Sibyll"
MATCH (b:ProperName)
WHERE b.Name = "Tripe"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Slytherin House"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Slytherin House"
MATCH (b:ProperName)
WHERE b.Name = "Snape"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Slytherin"
MATCH (b:ProperName)
WHERE b.Name = "UP"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Slytherin"
MATCH (b:ProperName)
WHERE b.Name = "Warrington"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Snape"
MATCH (b:ProperName)
WHERE b.Name = "Sprout"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Snape"
MATCH (b:ProperName)
WHERE b.Name = "Undetectable Poisons"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Spells"
MATCH (b:ProperName)
WHERE b.Name = "The Standard Book"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Spinnet"
MATCH (b:ProperName)
WHERE b.Name = "Weasley"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Spinnet"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Talk"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Stan"
MATCH (b:ProperName)
WHERE b.Name = "Talk"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Stink Pellets"
MATCH (b:ProperName)
WHERE b.Name = "Whizzing Worms"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Sunday"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "THAT"
MATCH (b:ProperName)
WHERE b.Name = "THIRTY-ZERO"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "THAT"
MATCH (b:ProperName)
WHERE b.Name = "YOU DIRTY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "THIRTY-ZERO"
MATCH (b:ProperName)
WHERE b.Name = "YOU DIRTY"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "UP"
MATCH (b:ProperName)
WHERE b.Name = "Warrington"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Unpredictable"
MATCH (b:ProperName)
WHERE b.Name = "When Fortunes Turn Foul"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Where"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Wales"
MATCH (b:ProperName)
WHERE b.Name = "Where"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "Weird"})
CREATE (:ProperName{ Name: "Wendelin"})
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Weird"
MATCH (b:ProperName)
WHERE b.Name = "Wendelin"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "What"
MATCH (b:ProperName)
WHERE b.Name = "Worst Is Coming"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Which Broomstick"
MATCH (b:ProperName)
WHERE b.Name = "Wood"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "Witchcraft"
MATCH (b:ProperName)
WHERE b.Name = "Wizardry"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
WITH 1 as dummy
MATCH (a:ProperName)
WHERE a.Name = "With"
MATCH (b:ProperName)
WHERE b.Name = "Wormtail"
WITH a,b
CREATE (a)-[:RELACIONA_SE_COM]->(b)
CREATE (:ProperName{ Name: "AAAAAAARRRGH"})
CREATE (:ProperName{ Name: "AAARGH"})
CREATE (:ProperName{ Name: "AAARRGGHH"})
CREATE (:ProperName{ Name: "AND TEA LEAVES"})
CREATE (:ProperName{ Name: "Aah"})
CREATE (:ProperName{ Name: "Abergavenny"})
CREATE (:ProperName{ Name: "Absolutely"})
CREATE (:ProperName{ Name: "After"})
CREATE (:ProperName{ Name: "Ah"})
CREATE (:ProperName{ Name: "Alas"})
CREATE (:ProperName{ Name: "All"})
CREATE (:ProperName{ Name: "An"})
CREATE (:ProperName{ Name: "And Professor Lupin"})
CREATE (:ProperName{ Name: "And Scabbers"})
CREATE (:ProperName{ Name: "And Snape"})
CREATE (:ProperName{ Name: "And You"})
CREATE (:ProperName{ Name: "And-he"})
CREATE (:ProperName{ Name: "Anyone"})
CREATE (:ProperName{ Name: "Anyway"})
CREATE (:ProperName{ Name: "Apothecary"})
CREATE (:ProperName{ Name: "Ar"})
CREATE (:ProperName{ Name: "Are"})
CREATE (:ProperName{ Name: "Aren"})
CREATE (:ProperName{ Name: "Around Easter"})
CREATE (:ProperName{ Name: "Arrived"})
CREATE (:ProperName{ Name: "As"})
CREATE (:ProperName{ Name: "Ask"})
CREATE (:ProperName{ Name: "Astronomy"})
CREATE (:ProperName{ Name: "Aunt"})
CREATE (:ProperName{ Name: "BEATEN THE KEEPER"})
CREATE (:ProperName{ Name: "BELIEVE IT"})
CREATE (:ProperName{ Name: "BIG MISTAKE"})
CREATE (:ProperName{ Name: "BLOOD"})
CREATE (:ProperName{ Name: "BOGGART IN THE WARDROBE"})
CREATE (:ProperName{ Name: "BY ORDER OF"})
CREATE (:ProperName{ Name: "Bang"})
CREATE (:ProperName{ Name: "Bath"})
CREATE (:ProperName{ Name: "Be"})
CREATE (:ProperName{ Name: "Beaky"})
CREATE (:ProperName{ Name: "Beaters"})
CREATE (:ProperName{ Name: "Beau"})
CREATE (:ProperName{ Name: "Because"})
CREATE (:ProperName{ Name: "Because Black"})
CREATE (:ProperName{ Name: "Bed"})
CREATE (:ProperName{ Name: "Bighead Boy"})
CREATE (:ProperName{ Name: "Bilius"})
CREATE (:ProperName{ Name: "Bin"})
CREATE (:ProperName{ Name: "Binky"})
CREATE (:ProperName{ Name: "Birthday"})
CREATE (:ProperName{ Name: "Blimey"})
CREATE (:ProperName{ Name: "Boggarts"})
CREATE (:ProperName{ Name: "Bought"})
CREATE (:ProperName{ Name: "Brand-new"})
CREATE (:ProperName{ Name: "Brilliant"})
CREATE (:ProperName{ Name: "Broaden"})
CREATE (:ProperName{ Name: "Broomstick Servicing Kit"})
CREATE (:ProperName{ Name: "Buckbeak"})
CREATE (:ProperName{ Name: "But"})
CREATE (:ProperName{ Name: "But Black"})
CREATE (:ProperName{ Name: "But Hogsmeade"})
CREATE (:ProperName{ Name: "But Mum"})
CREATE (:ProperName{ Name: "But Sirius Black"})
CREATE (:ProperName{ Name: "Butterbeer"})
CREATE (:ProperName{ Name: "Bye"})
CREATE (:ProperName{ Name: "CATCH THAT CAR"})
CREATE (:ProperName{ Name: "COME BACK AND PUT HER RIGHT"})
CREATE (:ProperName{ Name: "COME BACK IN HERE"})
CREATE (:ProperName{ Name: "COME ON"})
CREATE (:ProperName{ Name: "COMFORTED THE MURDERIN"})
CREATE (:ProperName{ Name: "Cadogan"})
CREATE (:ProperName{ Name: "Call"})
CREATE (:ProperName{ Name: "Can"})
CREATE (:ProperName{ Name: "Captains"})
CREATE (:ProperName{ Name: "Chang"})
CREATE (:ProperName{ Name: "Charing Cross Road"})
CREATE (:ProperName{ Name: "Charms"})
CREATE (:ProperName{ Name: "Check"})
CREATE (:ProperName{ Name: "Cheering Charm"})
CREATE (:ProperName{ Name: "Cheering Charms"})
CREATE (:ProperName{ Name: "Cho Chang"})
CREATE (:ProperName{ Name: "Chocoballs"})
CREATE (:ProperName{ Name: "Choo"})
CREATE (:ProperName{ Name: "Chris"})
CREATE (:ProperName{ Name: "Christmas Eve"})
CREATE (:ProperName{ Name: "Cleansweep Sevens"})
CREATE (:ProperName{ Name: "Clearly"})
CREATE (:ProperName{ Name: "Clever Crookshanks"})
CREATE (:ProperName{ Name: "Cockroach Cluster"})
CREATE (:ProperName{ Name: "Coincidence"})
CREATE (:ProperName{ Name: "Colin"})
CREATE (:ProperName{ Name: "Colin Creevey"})
CREATE (:ProperName{ Name: "Colonel Fubster"})
CREATE (:ProperName{ Name: "Comet"})
CREATE (:ProperName{ Name: "Coming"})
CREATE (:ProperName{ Name: "Concentrating"})
CREATE (:ProperName{ Name: "Cool"})
CREATE (:ProperName{ Name: "Cos"})
CREATE (:ProperName{ Name: "Couldn"})
CREATE (:ProperName{ Name: "Crackers"})
CREATE (:ProperName{ Name: "Cross"})
CREATE (:ProperName{ Name: "Crystal"})
CREATE (:ProperName{ Name: "Cup"})
CREATE (:ProperName{ Name: "DEFEAT"})
CREATE (:ProperName{ Name: "DEMENTOR"})
CREATE (:ProperName{ Name: "Daily"})
CREATE (:ProperName{ Name: "Daily Prophet"})
CREATE (:ProperName{ Name: "Dark"})
CREATE (:ProperName{ Name: "Davey Gudgeon"})
CREATE (:ProperName{ Name: "Dead"})
CREATE (:ProperName{ Name: "Dean"})
CREATE (:ProperName{ Name: "Dean Thomas"})
CREATE (:ProperName{ Name: "December"})
CREATE (:ProperName{ Name: "Definitely"})
CREATE (:ProperName{ Name: "Dementors"})
CREATE (:ProperName{ Name: "Did"})
CREATE (:ProperName{ Name: "Did YOU"})
CREATE (:ProperName{ Name: "Didn"})
CREATE (:ProperName{ Name: "Dig"})
CREATE (:ProperName{ Name: "Disguised"})
CREATE (:ProperName{ Name: "Disgusting"})
CREATE (:ProperName{ Name: "Dissendium"})
CREATE (:ProperName{ Name: "Does"})
CREATE (:ProperName{ Name: "Doing"})
CREATE (:ProperName{ Name: "Don"})
CREATE (:ProperName{ Name: "Down"})
CREATE (:ProperName{ Name: "Draco Malfoy"})
CREATE (:ProperName{ Name: "Draco Malfoys"})
CREATE (:ProperName{ Name: "Droobles Best Blowing Gum"})
CREATE (:ProperName{ Name: "Dudders"})
CREATE (:ProperName{ Name: "Duddy"})
CREATE (:ProperName{ Name: "Dudley"})
CREATE (:ProperName{ Name: "Dunno"})
CREATE (:ProperName{ Name: "Dursley-free"})
CREATE (:ProperName{ Name: "Dursleys"})
CREATE (:ProperName{ Name: "EH"})
CREATE (:ProperName{ Name: "EIGHT"})
CREATE (:ProperName{ Name: "ELEVEN"})
CREATE (:ProperName{ Name: "Each"})
CREATE (:ProperName{ Name: "Ear"})
CREATE (:ProperName{ Name: "Easily"})
CREATE (:ProperName{ Name: "Easy"})
CREATE (:ProperName{ Name: "Eat"})
CREATE (:ProperName{ Name: "Egyptian"})
CREATE (:ProperName{ Name: "Eh"})
CREATE (:ProperName{ Name: "Eleven Sickles"})
CREATE (:ProperName{ Name: "Er"})
CREATE (:ProperName{ Name: "Ernie"})
CREATE (:ProperName{ Name: "Errol"})
CREATE (:ProperName{ Name: "Everyone"})
CREATE (:ProperName{ Name: "Everything"})
CREATE (:ProperName{ Name: "Exactly"})
CREATE (:ProperName{ Name: "Excellent"})
CREATE (:ProperName{ Name: "Explain Why Muggles Need Electricity"})
CREATE (:ProperName{ Name: "FIFTEEN"})
CREATE (:ProperName{ Name: "FIREBOLT"})
CREATE (:ProperName{ Name: "FIVE"})
CREATE (:ProperName{ Name: "FOUR"})
CREATE (:ProperName{ Name: "FOURTEEN"})
CREATE (:ProperName{ Name: "FRIEND"})
CREATE (:ProperName{ Name: "FROM"})
CREATE (:ProperName{ Name: "Famous Harry Potter"})
CREATE (:ProperName{ Name: "Farewell"})
CREATE (:ProperName{ Name: "Fascinating"})
CREATE (:ProperName{ Name: "February"})
CREATE (:ProperName{ Name: "Fell"})
CREATE (:ProperName{ Name: "Fidelius Charm"})
CREATE (:ProperName{ Name: "Filthy"})
CREATE (:ProperName{ Name: "Finally"})
CREATE (:ProperName{ Name: "Fine"})
CREATE (:ProperName{ Name: "Firebold And"})
CREATE (:ProperName{ Name: "Firs"})
CREATE (:ProperName{ Name: "First Hogsmeade"})
CREATE (:ProperName{ Name: "Firstly"})
CREATE (:ProperName{ Name: "Fitch"})
CREATE (:ProperName{ Name: "Flame Freezing Charm"})
CREATE (:ProperName{ Name: "Fleetwood"})
CREATE (:ProperName{ Name: "Flibbertigibbet"})
CREATE (:ProperName{ Name: "Flint"})
CREATE (:ProperName{ Name: "Forbidden Forest"})
CREATE (:ProperName{ Name: "Forgot"})
CREATE (:ProperName{ Name: "Fortescue"})
CREATE (:ProperName{ Name: "Fortuna Major"})
CREATE (:ProperName{ Name: "Four"})
CREATE (:ProperName{ Name: "France"})
CREATE (:ProperName{ Name: "Fudge Flies"})
CREATE (:ProperName{ Name: "GET"})
CREATE (:ProperName{ Name: "GO GRYFFINDOR"})
CREATE (:ProperName{ Name: "GRUDGE"})
CREATE (:ProperName{ Name: "Gas"})
CREATE (:ProperName{ Name: "Gawd"})
CREATE (:ProperName{ Name: "Gee"})
CREATE (:ProperName{ Name: "Get"})
CREATE (:ProperName{ Name: "Getting"})
CREATE (:ProperName{ Name: "Ginny"})
CREATE (:ProperName{ Name: "Ginny Weasley"})
CREATE (:ProperName{ Name: "Go"})
CREATE (:ProperName{ Name: "Gobstones"})
CREATE (:ProperName{ Name: "God"})
CREATE (:ProperName{ Name: "Golden Snitch"})
CREATE (:ProperName{ Name: "Gone"})
CREATE (:ProperName{ Name: "Got"})
CREATE (:ProperName{ Name: "Gotta"})
CREATE (:ProperName{ Name: "Gr"})
CREATE (:ProperName{ Name: "Great"})
CREATE (:ProperName{ Name: "Great Hall"})
CREATE (:ProperName{ Name: "Grims"})
CREATE (:ProperName{ Name: "Grunnings"})
CREATE (:ProperName{ Name: "Gryffindor Quidditch"})
CREATE (:ProperName{ Name: "Gryffindor Seeker"})
CREATE (:ProperName{ Name: "Gryffindors"})
CREATE (:ProperName{ Name: "HB"})
CREATE (:ProperName{ Name: "HE"})
CREATE (:ProperName{ Name: "HERE"})
CREATE (:ProperName{ Name: "HIM"})
CREATE (:ProperName{ Name: "HOW DARE YOU GIVE THIS NUMBER TO PEOPLE LIKE"})
CREATE (:ProperName{ Name: "Ha"})
CREATE (:ProperName{ Name: "Halloween"})
CREATE (:ProperName{ Name: "Hand"})
CREATE (:ProperName{ Name: "Hang"})
CREATE (:ProperName{ Name: "Hasn"})
CREATE (:ProperName{ Name: "Have"})
CREATE (:ProperName{ Name: "Haven"})
CREATE (:ProperName{ Name: "Headmaster"})
CREATE (:ProperName{ Name: "Headmistress"})
CREATE (:ProperName{ Name: "Hear"})
CREATE (:ProperName{ Name: "Help"})
CREATE (:ProperName{ Name: "Here"})
CREATE (:ProperName{ Name: "Hermoine"})
CREATE (:ProperName{ Name: "Herrmone"})
CREATE (:ProperName{ Name: "High Street"})
CREATE (:ProperName{ Name: "High-Finish Polish"})
CREATE (:ProperName{ Name: "Hippogriffs"})
CREATE (:ProperName{ Name: "His"})
CREATE (:ProperName{ Name: "Hm"})
CREATE (:ProperName{ Name: "Hmm"})
CREATE (:ProperName{ Name: "Hmmm"})
CREATE (:ProperName{ Name: "Honestly"})
CREATE (:ProperName{ Name: "Honey Dukes"})
CREATE (:ProperName{ Name: "Honeyduke"})
CREATE (:ProperName{ Name: "Hooch"})
CREATE (:ProperName{ Name: "House Championship"})
CREATE (:ProperName{ Name: "Howler"})
CREATE (:ProperName{ Name: "Hufflepuffs"})
CREATE (:ProperName{ Name: "Huh"})
CREATE (:ProperName{ Name: "Humongous Bighead"})
CREATE (:ProperName{ Name: "Hurling Hex"})
CREATE (:ProperName{ Name: "IF"})
CREATE (:ProperName{ Name: "IT WASN"})
CREATE (:ProperName{ Name: "Ice Cream Parlor"})
CREATE (:ProperName{ Name: "Ice Mice"})
CREATE (:ProperName{ Name: "Id"})
CREATE (:ProperName{ Name: "If Neville"})
CREATE (:ProperName{ Name: "If Scabbers"})
CREATE (:ProperName{ Name: "If Snape"})
CREATE (:ProperName{ Name: "Ignore"})
CREATE (:ProperName{ Name: "Imagine"})
CREATE (:ProperName{ Name: "Impervius"})
CREATE (:ProperName{ Name: "Imps"})
CREATE (:ProperName{ Name: "In"})
CREATE (:ProperName{ Name: "Indeed"})
CREATE (:ProperName{ Name: "Ink"})
CREATE (:ProperName{ Name: "Inseparable"})
CREATE (:ProperName{ Name: "Inside"})
CREATE (:ProperName{ Name: "InterCity"})
CREATE (:ProperName{ Name: "Intermediate Transfiguration"})
CREATE (:ProperName{ Name: "Invisibility Cloak"})
CREATE (:ProperName{ Name: "Invisibility Cloaks"})
CREATE (:ProperName{ Name: "Irish International Side"})
CREATE (:ProperName{ Name: "Is"})
CREATE (:ProperName{ Name: "Jinxed"})
CREATE (:ProperName{ Name: "Jordan"})
CREATE (:ProperName{ Name: "Jus"})
CREATE (:ProperName{ Name: "Just"})
CREATE (:ProperName{ Name: "KNIGHT BUS"})
CREATE (:ProperName{ Name: "KNOCK HER OFF HER BROOM IF YOU HAVE TO"})
CREATE (:ProperName{ Name: "King"})
CREATE (:ProperName{ Name: "Kiss"})
CREATE (:ProperName{ Name: "Knight Bus"})
CREATE (:ProperName{ Name: "Knocking"})
CREATE (:ProperName{ Name: "Know"})
CREATE (:ProperName{ Name: "Know-Who"})
CREATE (:ProperName{ Name: "Knowing"})
CREATE (:ProperName{ Name: "LEAKY CAULDRON"})
CREATE (:ProperName{ Name: "LIONS FOR THE CUK"})
CREATE (:ProperName{ Name: "LOOK"})
CREATE (:ProperName{ Name: "Last"})
CREATE (:ProperName{ Name: "Later"})
CREATE (:ProperName{ Name: "Laughed"})
CREATE (:ProperName{ Name: "Lavender"})
CREATE (:ProperName{ Name: "Leaky Cauldron"})
CREATE (:ProperName{ Name: "Leave Scabbers"})
CREATE (:ProperName{ Name: "Let"})
CREATE (:ProperName{ Name: "Like"})
CREATE (:ProperName{ Name: "Listen"})
CREATE (:ProperName{ Name: "Local Deliveries Only"})
CREATE (:ProperName{ Name: "Locker"})
CREATE (:ProperName{ Name: "Look"})
CREATE (:ProperName{ Name: "Lord Voldemort"})
CREATE (:ProperName{ Name: "Lovely"})
CREATE (:ProperName{ Name: "Lucius Malfoy"})
CREATE (:ProperName{ Name: "Lucky"})
CREATE (:ProperName{ Name: "Lumos"})
CREATE (:ProperName{ Name: "Lures"})
CREATE (:ProperName{ Name: "MAP"})
CREATE (:ProperName{ Name: "MARAUDER"})
CREATE (:ProperName{ Name: "MARGE"})
CREATE (:ProperName{ Name: "MORE BRANDY"})
CREATE (:ProperName{ Name: "MY"})
CREATE (:ProperName{ Name: "Madam Hooch"})
CREATE (:ProperName{ Name: "Madam Pomfrey"})
CREATE (:ProperName{ Name: "Madam Rosemerta"})
CREATE (:ProperName{ Name: "Madam Rosmerta"})
CREATE (:ProperName{ Name: "Made"})
CREATE (:ProperName{ Name: "Magical Law Enforcement"})
CREATE (:ProperName{ Name: "Magical Menagerie"})
CREATE (:ProperName{ Name: "Make"})
CREATE (:ProperName{ Name: "Map"})
CREATE (:ProperName{ Name: "Marauder"})
CREATE (:ProperName{ Name: "Marsh"})
CREATE (:ProperName{ Name: "Marvelous"})
CREATE (:ProperName{ Name: "Me"})
CREATE (:ProperName{ Name: "Mean"})
CREATE (:ProperName{ Name: "Merry Christmas"})
CREATE (:ProperName{ Name: "Min"})
CREATE (:ProperName{ Name: "Mine"})
CREATE (:ProperName{ Name: "Mischief"})
CREATE (:ProperName{ Name: "Miss Granger"})
CREATE (:ProperName{ Name: "Mmm"})
CREATE (:ProperName{ Name: "Molly"})
CREATE (:ProperName{ Name: "Monday"})
CREATE (:ProperName{ Name: "Montague"})
CREATE (:ProperName{ Name: "Mother"})
CREATE (:ProperName{ Name: "Mount"})
CREATE (:ProperName{ Name: "Much"})
CREATE (:ProperName{ Name: "Mug"})
CREATE (:ProperName{ Name: "Muggle Underground"})
CREATE (:ProperName{ Name: "Muggles"})
CREATE (:ProperName{ Name: "Mummy"})
CREATE (:ProperName{ Name: "Must"})
CREATE (:ProperName{ Name: "My"})
CREATE (:ProperName{ Name: "My Head Boy"})
CREATE (:ProperName{ Name: "NIGHTMARE"})
CREATE (:ProperName{ Name: "NINE"})
CREATE (:ProperName{ Name: "NOOOOOOO"})
CREATE (:ProperName{ Name: "Nastily Exhausting Wizarding Tests"})
CREATE (:ProperName{ Name: "Nasty"})
CREATE (:ProperName{ Name: "Naturally"})
CREATE (:ProperName{ Name: "Nearly"})
CREATE (:ProperName{ Name: "Never"})
CREATE (:ProperName{ Name: "New"})
CREATE (:ProperName{ Name: "Nimbus"})
CREATE (:ProperName{ Name: "No"})
CREATE (:ProperName{ Name: "Noble"})
CREATE (:ProperName{ Name: "Nonsense"})
CREATE (:ProperName{ Name: "Nor"})
CREATE (:ProperName{ Name: "Norbert"})
CREATE (:ProperName{ Name: "North Tower"})
CREATE (:ProperName{ Name: "Not"})
CREATE (:ProperName{ Name: "Nothing"})
CREATE (:ProperName{ Name: "OF"})
CREATE (:ProperName{ Name: "OF MAGIC EMPLOYEE SCOOPS GRAND PRIZE"})
CREATE (:ProperName{ Name: "OF THE FAT FADY"})
CREATE (:ProperName{ Name: "ONE"})
CREATE (:ProperName{ Name: "OUCH"})
CREATE (:ProperName{ Name: "OUT"})
CREATE (:ProperName{ Name: "OY"})
CREATE (:ProperName{ Name: "Oddsbodikins"})
CREATE (:ProperName{ Name: "Of"})
CREATE (:ProperName{ Name: "Okay"})
CREATE (:ProperName{ Name: "Old"})
CREATE (:ProperName{ Name: "Ole"})
CREATE (:ProperName{ Name: "Oliver Wood"})
CREATE (:ProperName{ Name: "Only"})
CREATE (:ProperName{ Name: "Oo"})
CREATE (:ProperName{ Name: "Ooh"})
CREATE (:ProperName{ Name: "Ooooo"})
CREATE (:ProperName{ Name: "Ooooooh"})
CREATE (:ProperName{ Name: "Oooooooh"})
CREATE (:ProperName{ Name: "Or"})
CREATE (:ProperName{ Name: "Ordinary Wizarding Levels"})
CREATE (:ProperName{ Name: "Orrible"})
CREATE (:ProperName{ Name: "Ouch"})
CREATE (:ProperName{ Name: "Out"})
CREATE (:ProperName{ Name: "Ow"})
CREATE (:ProperName{ Name: "Oy"})
CREATE (:ProperName{ Name: "PATRONUS"})
CREATE (:ProperName{ Name: "PEOPLE LIKE YOU"})
CREATE (:ProperName{ Name: "POST"})
CREATE (:ProperName{ Name: "POTTER"})
CREATE (:ProperName{ Name: "PREDICTION"})
CREATE (:ProperName{ Name: "Pardon"})
CREATE (:ProperName{ Name: "Party"})
CREATE (:ProperName{ Name: "Parvati"})
CREATE (:ProperName{ Name: "Parvati Patil"})
CREATE (:ProperName{ Name: "Password"})
CREATE (:ProperName{ Name: "Patronus"})
CREATE (:ProperName{ Name: "Penelope Clearwater"})
CREATE (:ProperName{ Name: "Perce"})
CREATE (:ProperName{ Name: "Percy Weasley"})
CREATE (:ProperName{ Name: "Perhaps"})
CREATE (:ProperName{ Name: "Perhaps You"})
CREATE (:ProperName{ Name: "Petunia"})
CREATE (:ProperName{ Name: "Pity"})
CREATE (:ProperName{ Name: "Please"})
CREATE (:ProperName{ Name: "Pocket Sneakoscope"})
CREATE (:ProperName{ Name: "Pointedly"})
CREATE (:ProperName{ Name: "Poor"})
CREATE (:ProperName{ Name: "Possibly"})
CREATE (:ProperName{ Name: "Prang"})
CREATE (:ProperName{ Name: "Precisely"})
CREATE (:ProperName{ Name: "Pressure"})
CREATE (:ProperName{ Name: "Probably"})
CREATE (:ProperName{ Name: "Professer Trelawney"})
CREATE (:ProperName{ Name: "Professor Binn"})
CREATE (:ProperName{ Name: "Professor Binns"})
CREATE (:ProperName{ Name: "Professor Boggart Snape"})
CREATE (:ProperName{ Name: "Professor Flitwick"})
CREATE (:ProperName{ Name: "Professor Severus Snape"})
CREATE (:ProperName{ Name: "Professor Snape"})
CREATE (:ProperName{ Name: "Professor Sprout"})
CREATE (:ProperName{ Name: "Professor Trelawneys"})
CREATE (:ProperName{ Name: "Prophet"})
CREATE (:ProperName{ Name: "Psst"})
CREATE (:ProperName{ Name: "Punishment"})
CREATE (:ProperName{ Name: "Pushed"})
CREATE (:ProperName{ Name: "Put Yourself"})
CREATE (:ProperName{ Name: "QUIDDITCH FINAL"})
CREATE (:ProperName{ Name: "Quality Quidditch Supplies"})
CREATE (:ProperName{ Name: "Quiet"})
CREATE (:ProperName{ Name: "Quite"})
CREATE (:ProperName{ Name: "RE DOIN"})
CREATE (:ProperName{ Name: "RE NOT TO GO WANDERIN"})
CREATE (:ProperName{ Name: "RON"})
CREATE (:ProperName{ Name: "Ravenclaw Chaser"})
CREATE (:ProperName{ Name: "Ready"})
CREATE (:ProperName{ Name: "Really"})
CREATE (:ProperName{ Name: "Reckon Fred"})
CREATE (:ProperName{ Name: "Red Caps"})
CREATE (:ProperName{ Name: "Reveal"})
CREATE (:ProperName{ Name: "Riddikulus"})
CREATE (:ProperName{ Name: "Righ"})
CREATE (:ProperName{ Name: "Right"})
CREATE (:ProperName{ Name: "Righto"})
CREATE (:ProperName{ Name: "Ripper"})
CREATE (:ProperName{ Name: "Room"})
CREATE (:ProperName{ Name: "Rubeus Hagrid"})
CREATE (:ProperName{ Name: "Ruddy"})
CREATE (:ProperName{ Name: "SAVED IT"})
CREATE (:ProperName{ Name: "SCABBERS"})
CREATE (:ProperName{ Name: "SCHOOL"})
CREATE (:ProperName{ Name: "SEVEN"})
CREATE (:ProperName{ Name: "SHUT UP"})
CREATE (:ProperName{ Name: "SIX"})
CREATE (:ProperName{ Name: "SIXTEEN"})
CREATE (:ProperName{ Name: "SMACK"})
CREATE (:ProperName{ Name: "STILL AT LARGE"})
CREATE (:ProperName{ Name: "Saturday"})
CREATE (:ProperName{ Name: "Say You-Know-Who"})
CREATE (:ProperName{ Name: "Scared"})
CREATE (:ProperName{ Name: "Scary-lookin"})
CREATE (:ProperName{ Name: "School"})
CREATE (:ProperName{ Name: "Seamus Finnigan"})
CREATE (:ProperName{ Name: "Second Head Boy"})
CREATE (:ProperName{ Name: "Secondly"})
CREATE (:ProperName{ Name: "Send"})
CREATE (:ProperName{ Name: "Seriously"})
CREATE (:ProperName{ Name: "Setting"})
CREATE (:ProperName{ Name: "Settle"})
CREATE (:ProperName{ Name: "Seventy"})
CREATE (:ProperName{ Name: "Severus Snape"})
CREATE (:ProperName{ Name: "Sh"})
CREATE (:ProperName{ Name: "Shall"})
CREATE (:ProperName{ Name: "Shame"})
CREATE (:ProperName{ Name: "Shh"})
CREATE (:ProperName{ Name: "Show-offs"})
CREATE (:ProperName{ Name: "Shrieking Shades"})
CREATE (:ProperName{ Name: "Shrinking Solution"})
CREATE (:ProperName{ Name: "Sight"})
CREATE (:ProperName{ Name: "Silence"})
CREATE (:ProperName{ Name: "Simply"})
CREATE (:ProperName{ Name: "Sir"})
CREATE (:ProperName{ Name: "Sir Cadogan"})
CREATE (:ProperName{ Name: "Sit"})
CREATE (:ProperName{ Name: "Sleep"})
CREATE (:ProperName{ Name: "Slytherins"})
CREATE (:ProperName{ Name: "Sneakoscope"})
CREATE (:ProperName{ Name: "So"})
CREATE (:ProperName{ Name: "Someone"})
CREATE (:ProperName{ Name: "Something"})
CREATE (:ProperName{ Name: "Sorry"})
CREATE (:ProperName{ Name: "Sort"})
CREATE (:ProperName{ Name: "Sorting"})
CREATE (:ProperName{ Name: "Spare"})
CREATE (:ProperName{ Name: "Special Effects"})
CREATE (:ProperName{ Name: "Spect"})
CREATE (:ProperName{ Name: "Spellotape"})
CREATE (:ProperName{ Name: "St"})
CREATE (:ProperName{ Name: "Stan Shunpike"})
CREATE (:ProperName{ Name: "Stand"})
CREATE (:ProperName{ Name: "Stay"})
CREATE (:ProperName{ Name: "Stick"})
CREATE (:ProperName{ Name: "Still"})
CREATE (:ProperName{ Name: "Strip"})
CREATE (:ProperName{ Name: "Strong"})
CREATE (:ProperName{ Name: "Stuck"})
CREATE (:ProperName{ Name: "Stupid"})
CREATE (:ProperName{ Name: "Superb"})
CREATE (:ProperName{ Name: "Suppose You"})
CREATE (:ProperName{ Name: "Surely"})
CREATE (:ProperName{ Name: "T-shirt"})
CREATE (:ProperName{ Name: "TALK"})
CREATE (:ProperName{ Name: "TEN"})
CREATE (:ProperName{ Name: "THAT WAS DELIBERATE"})
CREATE (:ProperName{ Name: "THE FIREBOLT"})
CREATE (:ProperName{ Name: "THE MINISTRY OF MAGIC"})
CREATE (:ProperName{ Name: "THERE IS NO HARRY POTTER HERE"})
CREATE (:ProperName{ Name: "THIRTEEN"})
CREATE (:ProperName{ Name: "THREE"})
CREATE (:ProperName{ Name: "TO"})
CREATE (:ProperName{ Name: "TRAITOR"})
CREATE (:ProperName{ Name: "TRELAWNEY"})
CREATE (:ProperName{ Name: "TWELVE"})
CREATE (:ProperName{ Name: "TWO"})
CREATE (:ProperName{ Name: "Take"})
CREATE (:ProperName{ Name: "Tangled"})
CREATE (:ProperName{ Name: "Taster"})
CREATE (:ProperName{ Name: "Team"})
CREATE (:ProperName{ Name: "Tell"})
CREATE (:ProperName{ Name: "Tha"})
CREATE (:ProperName{ Name: "Thank"})
CREATE (:ProperName{ Name: "Thanks"})
CREATE (:ProperName{ Name: "That"})
CREATE (:ProperName{ Name: "That Committee"})
CREATE (:ProperName{ Name: "The"})
CREATE (:ProperName{ Name: "The Knight Bus"})
CREATE (:ProperName{ Name: "The Patronus"})
CREATE (:ProperName{ Name: "Them"})
CREATE (:ProperName{ Name: "Them Disposal"})
CREATE (:ProperName{ Name: "Thinking Of"})
CREATE (:ProperName{ Name: "This Friday"})
CREATE (:ProperName{ Name: "This Potter"})
CREATE (:ProperName{ Name: "Thomas"})
CREATE (:ProperName{ Name: "Thought"})
CREATE (:ProperName{ Name: "Three"})
CREATE (:ProperName{ Name: "Tom"})
CREATE (:ProperName{ Name: "Too"})
CREATE (:ProperName{ Name: "Transfiguration Today"})
CREATE (:ProperName{ Name: "Trevor"})
CREATE (:ProperName{ Name: "Trouble"})
CREATE (:ProperName{ Name: "Trust Malfoy"})
CREATE (:ProperName{ Name: "Tuesday"})
CREATE (:ProperName{ Name: "UNUSUAL TASTES"})
CREATE (:ProperName{ Name: "Uh-oh"})
CREATE (:ProperName{ Name: "Unemployed"})
CREATE (:ProperName{ Name: "Until"})
CREATE (:ProperName{ Name: "Usual"})
CREATE (:ProperName{ Name: "VERSUS RAVENCLAW"})
CREATE (:ProperName{ Name: "Vernon"})
CREATE (:ProperName{ Name: "Vernon Dursley"})
CREATE (:ProperName{ Name: "Very"})
CREATE (:ProperName{ Name: "WANT"})
CREATE (:ProperName{ Name: "WEASLEY"})
CREATE (:ProperName{ Name: "WHAM"})
CREATE (:ProperName{ Name: "WHAT"})
CREATE (:ProperName{ Name: "WHO ARE YOU"})
CREATE (:ProperName{ Name: "WHO IS THIS"})
CREATE (:ProperName{ Name: "Waddiwasi"})
CREATE (:ProperName{ Name: "Wardrobes"})
CREATE (:ProperName{ Name: "Was Binky"})
CREATE (:ProperName{ Name: "Water"})
CREATE (:ProperName{ Name: "Way"})
CREATE (:ProperName{ Name: "Weak"})
CREATE (:ProperName{ Name: "Welcome"})
CREATE (:ProperName{ Name: "Were"})
CREATE (:ProperName{ Name: "Werewolves"})
CREATE (:ProperName{ Name: "Wh"})
CREATE (:ProperName{ Name: "When"})
CREATE (:ProperName{ Name: "Which"})
CREATE (:ProperName{ Name: "Who"})
CREATE (:ProperName{ Name: "Whomping Willow"})
CREATE (:ProperName{ Name: "Will"})
CREATE (:ProperName{ Name: "Wish"})
CREATE (:ProperName{ Name: "Won"})
CREATE (:ProperName{ Name: "Wonder"})
CREATE (:ProperName{ Name: "World Championship"})
CREATE (:ProperName{ Name: "World Cup"})
CREATE (:ProperName{ Name: "Worried"})
CREATE (:ProperName{ Name: "Worse"})
CREATE (:ProperName{ Name: "Woss"})
CREATE (:ProperName{ Name: "Would"})
CREATE (:ProperName{ Name: "YEH"})
CREATE (:ProperName{ Name: "YEH THINK YOU"})
CREATE (:ProperName{ Name: "YOU CHEATING SCUM"})
CREATE (:ProperName{ Name: "YOU COME NEAR MY FAMILY"})
CREATE (:ProperName{ Name: "YOU DO NOT ATTACK THE KEEPER UNLESS THE QUAFFLE IS WITHIN THE SCORING AREA"})
CREATE (:ProperName{ Name: "YWve"})
CREATE (:ProperName{ Name: "Yeah"})
CREATE (:ProperName{ Name: "Yeh"})
CREATE (:ProperName{ Name: "Yep"})
CREATE (:ProperName{ Name: "Yer"})
CREATE (:ProperName{ Name: "Yes"})
CREATE (:ProperName{ Name: "Yet"})
CREATE (:ProperName{ Name: "Yo"})
CREATE (:ProperName{ Name: "Your"})
CREATE (:ProperName{ Name: "Yourself"})
CREATE (:ProperName{ Name: "ZERO TO GRYFFINDOR"})
